/*
 * Smoke test for the data pipeline.
 *
 * Run with `npm run smoke`.  Validates the data files generated by
 * `npm run build:data` are structurally sound and contain the expected
 * entries.  Exits non-zero on the first failed assertion.
 */

const fs = require('fs');
const path = require('path');
const { pathToFileURL } = require('url');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'src', 'data');
const PUB = path.join(ROOT, 'public');

function check(label, cond, detail) {
  if (cond) {
    console.log(`  ok   ${label}`);
    return true;
  }
  console.error(`  FAIL ${label}${detail ? ' - ' + detail : ''}`);
  failed++;
  return false;
}

let failed = 0;

async function importEsm(relPath) {
  return import(pathToFileURL(path.join(ROOT, relPath)).href);
}

function readJson(rel) {
  return JSON.parse(fs.readFileSync(path.join(ROOT, rel), 'utf8'));
}

function installFetchShim() {
  globalThis.fetch = async (url) => {
    const rel = String(url).replace(/^\//, '');
    const candidates = [path.join(ROOT, rel), path.join(PUB, rel)];
    for (const filePath of candidates) {
      if (fs.existsSync(filePath)) {
        const data = await fs.promises.readFile(filePath, 'utf8');
        return {
          ok: true,
          status: 200,
          json: async () => JSON.parse(data),
        };
      }
    }
    return { ok: false, status: 404, json: async () => null };
  };
  globalThis.localStorage = {
    _s: new Map(),
    getItem(k) { return this._s.has(k) ? this._s.get(k) : null; },
    setItem(k, v) { this._s.set(k, String(v)); },
    removeItem(k) { this._s.delete(k); },
  };
}

async function main() {
  installFetchShim();

  console.log('Static data files (src/data/)');

  const { ENTRIES: ITEMS } = await importEsm('src/data/items.js');
  const { ENTRIES: ABILITIES } = await importEsm('src/data/abilities.js');

  check('items.js has 583 entries', Object.keys(ITEMS).length === 583, `got ${Object.keys(ITEMS).length}`);
  check('items.js includes merged mod patches', ITEMS.absorbbulb && ITEMS.absorbbulb.isNonstandard === 'Past');
  check('Leftovers is legal in standard (no isNonstandard)', ITEMS.leftovers && ITEMS.leftovers.isNonstandard === undefined);
  check('Absorb Bulb is Past in the merged table', ITEMS.absorbbulb && ITEMS.absorbbulb.isNonstandard === 'Past');

  check('abilities.js has 318 entries', Object.keys(ABILITIES).length === 318, `got ${Object.keys(ABILITIES).length}`);
  check('overgrow ability exists', !!ABILITIES.overgrow);
  check('overgrow has name "Overgrow"', ABILITIES.overgrow && ABILITIES.overgrow.name === 'Overgrow');

  console.log('\nRegulation bundles (src/data/regulations/)');

  const mA = await importEsm('src/data/regulations/m-a.js');

  check('m-a.js exports KEY', mA.KEY === 'm-a');
  check('m-a.js exports LABEL', typeof mA.LABEL === 'string' && mA.LABEL.length > 0);
  check('m-a.js POKEMON has 276 species', mA.POKEMON.size === 276, `got ${mA.POKEMON.size}`);
  check('m-a.js POKEMON contains "Venusaur"', mA.POKEMON.has('Venusaur'));
  check('m-a.js POKEMON contains "Venusaur-Mega"', mA.POKEMON.has('Venusaur-Mega'));
  check('m-a.js POKEMON contains "Aegislash-Blade"', mA.POKEMON.has('Aegislash-Blade'));
  check('m-a.js POKEMON contains "Castform-Rainy"', mA.POKEMON.has('Castform-Rainy'));
  check('m-a.js POKEMON does NOT contain "Bulbasaur"', !mA.POKEMON.has('Bulbasaur'));
  check('m-a.js POKEMON does NOT contain "Pikachu-Belle"', !mA.POKEMON.has('Pikachu-Belle'));
  check('m-a.js ITEMS has 117 entries', mA.ITEMS.size === 117, `got ${mA.ITEMS.size}`);
  check('m-a.js ITEMS contains "leftovers"', mA.ITEMS.has('leftovers'));
  check('m-a.js ITEMS contains "venusaurite"', mA.ITEMS.has('venusaurite'));
  check('m-a.js ITEMS does NOT contain "absorbbulb"', !mA.ITEMS.has('absorbbulb'));
  check('m-a.js ABILITIES has 314 entries (per-regulation allowlist)', mA.ABILITIES.size === 314, `got ${mA.ABILITIES.size}`);
  check('m-a.js ABILITIES contains "overgrow"', mA.ABILITIES.has('overgrow'));
  check('m-a.js ABILITIES contains "dragonize" (un-banned by mod)', mA.ABILITIES.has('dragonize'));
  check('m-a.js ABILITIES does NOT contain "mountaineer" (CAP)', !mA.ABILITIES.has('mountaineer'));
  check('m-a.js exports IS_NONSTANDARD Set', mA.IS_NONSTANDARD instanceof Set && mA.IS_NONSTANDARD.has('Past'));
  check('m-a.js LEARNSETS_URL is /regulations/m-a/learnsets.json', mA.LEARNSETS_URL === '/regulations/m-a/learnsets.json');

  const barrel = await importEsm('src/data/regulations/index.js');
  check('regulations/index.js barrel re-exports m-a', !!barrel.m_a);

  console.log('\nPer-regulation learnset JSON (public/regulations/)');

  const maLearnsets = readJson('public/regulations/m-a/learnsets.json');
  const maLearnsetIds = Object.keys(maLearnsets);

  check('m-a learnsets has 276 species', maLearnsetIds.length === 276, `got ${maLearnsetIds.length}`);
  check('m-a learnsets has venusaur', !!maLearnsets.venusaur);
  check('m-a learnsets has aegislash', !!maLearnsets.aegislash);
  check('m-a learnsets has aegislashblade (form merged)', !!maLearnsets.aegislashblade);
  check('m-a learnsets has castformrainy (form merged)', !!maLearnsets.castformrainy);
  check('m-a learnsets has rotom', !!maLearnsets.rotom);
  check('m-a learnsets has rotomheat (form merged with base)', !!maLearnsets.rotomheat);
  check('m-a learnsets has rotomwash (form merged with base)', !!maLearnsets.rotomwash);
  check('m-a learnsets has floettemega (inherited from floetteeternal)', !!maLearnsets.floettemega);
  check('floettemega has same moves as floetteeternal (inherited)',
    JSON.stringify(maLearnsets.floettemega) === JSON.stringify(maLearnsets.floetteeternal));

  check('aegislashblade has same moves as aegislash (merge)',
    JSON.stringify(maLearnsets.aegislashblade) === JSON.stringify(maLearnsets.aegislash));

  check('rotomheat has form-specific overheat',
    maLearnsets.rotomheat.includes('overheat'));
  check('rotomheat has 43 moves (42 from rotom + overheat)',
    maLearnsets.rotomheat.length === 43,
    `got ${maLearnsets.rotomheat.length}`);
  check('rotomheat includes all rotom moves',
    maLearnsets.rotom.every((m) => maLearnsets.rotomheat.includes(m)));

  check('venusaur does NOT have absorb (banned by M-A moves.ts)', !maLearnsets.venusaur.includes('absorb'));
  check('venusaur HAS acidspray (9M)', maLearnsets.venusaur.includes('acidspray'));
  check('per-regulation learnset is array of move IDs (no codes)', Array.isArray(maLearnsets.venusaur) && maLearnsets.venusaur.every((x) => typeof x === 'string'));

  console.log('\nPublic data files (public/)');

  const dex = readJson('public/pokedex.json');
  const moves = readJson('public/moves.json');
  const learnsets = readJson('public/learnsets.json');

  check('pokedex.json has 1300+ species', Object.keys(dex).length > 1300, `got ${Object.keys(dex).length}`);
  check('pokedex.json contains "venusaur"', !!dex.venusaur);
  check('pokedex.json contains "venusaurmega"', !!dex.venusaurmega);
  check('pokedex.json contains "aegislashblade"', !!dex.aegislashblade);
  check('pokedex.json contains "castformrainy"', !!dex.castformrainy);
  check('pokedex.json keeps "bulbasaur" (standard in Showdown; regulation filters exclude it)', !!dex.bulbasaur);
  check('pokedex.json keeps past forms like "pikachucosplay"', !!dex.pikachucosplay);
  check('pokedex.json keeps "pichuspikyeared" (a Past form)', !!dex.pichuspikyeared);
  check('pokedex.json drops CAP forms like "syclar"', !dex.syclar);
  check('pokedex.json drops "missingno" (no base stats)', !dex.missingno);
  check('pokedex.json carries isNonstandard in "ns" field', dex.bulbasaur && dex.bulbasaur.ns === null);

  check('moves.json has 900+ moves', Object.keys(moves).length > 900, `got ${Object.keys(moves).length}`);
  check('moves.json: tackle exists', !!moves.tackle);
  check('moves.json: tackle has basePower 40', moves.tackle && moves.tackle.basePower === 40);

  check('learnsets.json has 1000+ species (master fallback for "all" regulation)', Object.keys(learnsets).length > 1000, `got ${Object.keys(learnsets).length}`);
  check('learnsets.json: venusaur has at least 30 moves',
    learnsets.venusaur && Object.keys(learnsets.venusaur).length >= 30,
    learnsets.venusaur ? `got ${Object.keys(learnsets.venusaur).length}` : 'missing');
  check('learnsets.json: bulbasaur kept (standard species; regulation filter excludes it)',
    !!learnsets.bulbasaur);

  console.log('\nRegulation registry');

  const { getRegulation, REGULATIONS, DEFAULT_REG } = await importEsm('src/lib/regulations.js');
  const { isItemLegal } = await importEsm('src/lib/items.js');
  const { isAbilityLegal } = await importEsm('src/lib/abilities.js');

  const ma = getRegulation('m-a');
  const all = getRegulation('all');
  check('regulation "m-a" exists', !!ma);
  check('regulation "all" exists', !!all);
  check('DEFAULT_REG is the first bundle key', DEFAULT_REG === 'm-a');
  check('unknown regulation key falls back to default', getRegulation('nope').key === DEFAULT_REG);
  check('m-a pool size is 276', ma.pool && ma.pool.size === 276);
  check('m-a items allowlist size is 117', ma.items && ma.items.size === 117, `got ${ma.items && ma.items.size}`);
  check('m-a abilities allowlist size is 314', ma.abilities && ma.abilities.size === 314, `got ${ma.abilities && ma.abilities.size}`);
  check('"all" regulation has no abilities allowlist (falls back to isNonstandard)', all.abilities === null);
  check('m-a learnsetsUrl is /regulations/m-a/learnsets.json', ma.learnsetsUrl === '/regulations/m-a/learnsets.json');
  check('"all" regulation has no learnsetsUrl (falls back to master)', all.learnsetsUrl === null);

  check('isItemLegal("leftovers", "m-a") === true', isItemLegal('leftovers', 'm-a'));
  check('isItemLegal("venusaurite", "m-a") === true (un-banned by mod)', isItemLegal('venusaurite', 'm-a'));
  check('isItemLegal("absorbbulb", "m-a") === false (Past)', !isItemLegal('absorbbulb', 'm-a'));
  check('isItemLegal("blackbelt", "all") === true (standard item stays legal in "all")', isItemLegal('blackbelt', 'all'));
  check('isItemLegal("spelltag", "m-a") === true (mod un-banned)', isItemLegal('spelltag', 'm-a'));

  check('isAbilityLegal("overgrow", "m-a") === true', isAbilityLegal('overgrow', 'm-a'));
  check('isAbilityLegal("overgrow", "all") === true', isAbilityLegal('overgrow', 'all'));
  check('isAbilityLegal("dragonize", "m-a") === true (un-banned by mod)', isAbilityLegal('dragonize', 'm-a'));
  check('isAbilityLegal("mountaineer", "m-a") === false (CAP, blocked by IS_NONSTANDARD)', !isAbilityLegal('mountaineer', 'm-a'));
  check('isAbilityLegal("mountaineer", "all") === false (CAP, blocked by IS_NONSTANDARD)', !isAbilityLegal('mountaineer', 'all'));

  console.log('\nPer-regulation learnset loading');

  const { getMovesWithDetails, loadLearnsets } = await importEsm('src/lib/learnsets.js');
  const { loadMoves } = await importEsm('src/lib/moves.js');

  await loadMoves();
  await loadLearnsets('m-a');
  await loadLearnsets('all');

  const maVenusaur = getMovesWithDetails('venusaur', 'm-a');
  const maAegislashBlade = getMovesWithDetails('aegislashblade', 'm-a');
  const maRotomHeat = getMovesWithDetails('rotomheat', 'm-a');
  const allVenusaur = getMovesWithDetails('venusaur', 'all');

  check('m-a venusaur has at least 30 legal moves', maVenusaur.length >= 30, `got ${maVenusaur.length}`);
  check('m-a venusaur does NOT include absorb (banned by M-A moves.ts)',
    !maVenusaur.some((m) => m.id === 'absorb'));
  check('m-a aegislashblade uses aegislash learnset (form merged)',
    JSON.stringify(maAegislashBlade.map((m) => m.id).sort()) ===
    JSON.stringify(getMovesWithDetails('aegislash', 'm-a').map((m) => m.id).sort()));
  check('m-a rotomheat includes overheat (form-specific merge)',
    maRotomHeat.some((m) => m.id === 'overheat'));
  check('m-a rotomheat includes all rotom moves (form merged with base)',
    maLearnsets.rotom.every((m) => maRotomHeat.some((move) => move.id === m)));
  check('getMovesWithDetails output has no codes/via fields',
    maVenusaur.every((m) => !('codes' in m) && !('via' in m)));
  check('all venusaur has at least as many legal moves as m-a (full learnset)', allVenusaur.length >= maVenusaur.length);

  await runFrozenRegulationTest();

  console.log('\nDone.');
  if (failed > 0) {
    console.error(`\n${failed} assertion(s) failed.`);
    process.exit(1);
  }
  process.exit(0);
}

async function runFrozenRegulationTest() {
  console.log('\nFrozen regulation handling');

  const SCRIPTS = path.join(ROOT, 'scripts');
  const REG_DIR = path.join(ROOT, 'src', 'data', 'regulations');
  const PUB_REG_DIR = path.join(ROOT, 'public', 'regulations');
  const configPath = path.join(SCRIPTS, 'regulations-config.cjs');
  const configRequire = require(configPath);

  const testKey = 'test-frozen-' + Date.now();
  const testBundlePath = path.join(REG_DIR, testKey + '.js');
  const testLearnsetDir = path.join(PUB_REG_DIR, testKey);
  const testLearnsetPath = path.join(testLearnsetDir, 'learnsets.json');
  const dummyBundle =
    '// AUTO-GENERATED TEST FIXTURE - do not commit\n' +
    'export const KEY = ' + JSON.stringify(testKey) + ';\n' +
    'export const LABEL = "Test Frozen";\n' +
    'export const POKEMON = new Set(["Venusaur"]);\n' +
    'export const ITEMS = new Set(["leftovers"]);\n' +
    'export const ABILITIES = new Set(["overgrow"]);\n' +
    'export const IS_NONSTANDARD = new Set(["Past"]);\n' +
    'export const LEARNSETS_URL = "/regulations/' + testKey + '/learnsets.json";\n';
  const dummyLearnset = '{"venusaur":["tackle"]}';

  fs.mkdirSync(testLearnsetDir, { recursive: true });
  fs.writeFileSync(testBundlePath, dummyBundle);
  fs.writeFileSync(testLearnsetPath, dummyLearnset);

  const { spawnSync } = require('child_process');
  const originalConfig = fs.readFileSync(configPath, 'utf8');

  function cleanupAndRebuild() {
    fs.writeFileSync(configPath, originalConfig);
    if (fs.existsSync(testBundlePath)) fs.unlinkSync(testBundlePath);
    if (fs.existsSync(testLearnsetDir)) fs.rmSync(testLearnsetDir, { recursive: true, force: true });
    const r = spawnSync(process.execPath, [path.join(SCRIPTS, 'build-regulations.cjs')], { stdio: 'pipe' });
    if (r.status !== 0) console.error('Cleanup rebuild failed:', r.stderr.toString());
  }

  try {
    const frozenEntry =
      '  {\n' +
      '    key: ' + JSON.stringify(testKey) + ',\n' +
      '    label: "Test Frozen",\n' +
      '    modDir: "champions",\n' +
      '    isNonstandard: ["Past"],\n' +
      '    excludedRosterNonstandard: ["Past"],\n' +
      '    frozen: true,\n' +
      '  },\n';
    // Insert the frozen entry just before the closing REGULATIONS array.
    const marker = '\n];\n\n/**';
    const markerIndex = originalConfig.indexOf(marker);
    if (markerIndex === -1) throw new Error('Could not find REGULATIONS array terminator');
    const modifiedConfig =
      originalConfig.slice(0, markerIndex) +
      '\n' + frozenEntry + '];\n\n/**' +
      originalConfig.slice(markerIndex + marker.length);
    fs.writeFileSync(configPath, modifiedConfig);

    const r = spawnSync(process.execPath, [path.join(SCRIPTS, 'build-regulations.cjs')], { stdio: 'pipe' });
    check('frozen regulation: build succeeds', r.status === 0, 'exit ' + r.status + '\n' + (r.stderr ? r.stderr.toString() : ''));
    const stdout = r.stdout ? r.stdout.toString() : '';
    check('frozen regulation: build logs the FROZEN skip line', stdout.includes('FROZEN (skipping build'));

    const bundleAfter = fs.readFileSync(testBundlePath, 'utf8');
    check('frozen regulation: bundle is preserved (not overwritten)', bundleAfter === dummyBundle);
    const learnsetAfter = fs.readFileSync(testLearnsetPath, 'utf8');
    check('frozen regulation: learnset is preserved (not overwritten)', learnsetAfter === dummyLearnset);

    const barrelPath = path.join(REG_DIR, 'index.js');
    const barrel = fs.readFileSync(barrelPath, 'utf8');
    const safeIdent = testKey.replace(/[^a-zA-Z0-9_$]/g, '_');
    check('frozen regulation: barrel re-exports it as namespace', barrel.includes('as ' + safeIdent));
    check('frozen regulation: barrel references its bundle file', barrel.includes('from "./' + testKey + '.js"'));

    delete require.cache[require.resolve(configPath)];
    const re = require(configPath);
    const cfg = re.REGULATIONS.find((r) => r.key === testKey);
    check('frozen regulation: visible in REGULATIONS list with frozen:true', !!cfg && cfg.frozen === true);
  } finally {
    cleanupAndRebuild();
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
